### ISSUE TITLE
Default CSS template for HtmlFormatterType.Css

### ISSUE THREAD

**Issue by kostas-baltsoft** [wbaldoumas/markdown-colorcode#116]
## Problem Statement

In my case, the inlined CSS option is not a suitable option, because it conflicts with my own styling that I want to have on the code wrapper. It is impossible to overwrite it from my CSS because the parent div element doesn't have a class or something to target it.
So I decided to go with ```HtmlFormatterType.Css``` which is a great option. 

However, I cannot find the default CSS file for the provided classes. I mean, it must be somewhere, right? I want to apply the same styling as per inlined CSS but have the option to add my own code to the CSS file.

## Proposed Solution

Place the default CSS template in the repository for easy download (assets folder, maybe?)

**Comment by wbaldoumas** [comment]
@kostas-baltsoft this library doesn't generate its own CSS file when the `HtmlFormatterType.Css` option is used. Markdown.ColorCode uses the ColorCode-Universal library in order to generate styling. 

When you select `HtmlFormatterType.Css`, under the hood the ColorCode-Universal [HtmlClassFormatter](https://github.com/CommunityToolkit/ColorCode-Universal/blob/main/ColorCode.HTML/HtmlClassFormatter.cs#L22-L29) gets used. I've included the CSS generated by its `GetCSSString` when `StyleDictionary.DefaultDark` is used in the `assets/css` directory of this repository. 

Please take a look and let me know what you think.

**Comment by kostas-baltsoft** [comment]
Perfect, precisely what I was looking for!
