### ISSUE TITLE
Use `HtmlClassFormatter.GetCSSString`

### ISSUE THREAD

**Issue by johnW-ret** [wbaldoumas/markdown-colorcode#162]
## Problem Statement

Currently,

```csharp
var builder = new MarkdownPipelineBuilder()
    // ...
    .UseColorCode(HtmlFormatterType.Css, /* ... */)
    // ...
    ;   
```
outputs HTML of the sort:

```html
<div class="FSharp">
   <pre>
      ...
      <span class="string">"foo"</span>
      ...
   </pre>
</div>
```

To actually get styling, you need the CSS code from [`HtmlClassFormatter.GetCSSString`](https://github.com/CommunityToolkit/ColorCode-Universal/blob/34878acb21e7688d37b6dd8acaee29feb9fbfc85/ColorCode.HTML/HtmlClassFormatter.cs#L63C9-L90C10) from `ColorCode`.

Forgive me if I just misunderstand the code, but this library never calls `HtmlClassFormatter.GetCSSString` and `HtmlClassFormatter` is only [stored as a `private readonly` field](https://github.com/wbaldoumas/markdown-colorcode/blob/fbee2af3483c7e5e814851b8bf9747c3daf335fc/src/Markdown.ColorCode/Internal/HtmlCssFormatter.cs#L6) in a `sealed` class, so there is currently no way to get ths CSS styling out of this library.
 
## Proposed Solution

CSS should be placed in an inline `style` tag next to the rendered HTML.

## Alternatives Considered

The aforementioned solution would cause style duplication (?), but it's also the simplest solution that works.

**Comment by wbaldoumas** [comment]
@johnW-ret thanks for your interest in Markdown.ColorCode and for opening this issue. This is similar to https://github.com/wbaldoumas/markdown-colorcode/issues/116.

The idea behind `HtmlFormatterType.Css` is to allow users of this library to customize their syntax coloring using their own CSS files. Rather than forcing the output of [HtmlClassFormatter.GetCSSString](https://github.com/CommunityToolkit/ColorCode-Universal/blob/34878acb21e7688d37b6dd8acaee29feb9fbfc85/ColorCode.HTML/HtmlClassFormatter.cs#L63C9-L90C10) into the generated HTML, users should specify their own CSS styling.

You can find (and use as-is or customize) the default CSS needed for `HtmlFormatterType.Css` [here](https://github.com/wbaldoumas/markdown-colorcode/blob/main/assets/css/default.css).

As a follow up, is there a documentation improvement that can be made that would make this more obvious?
