### ISSUE TITLE
Nullreference exception on .net6 

### ISSUE THREAD

**Issue by WillEastbury** [wbaldoumas/markdown-colorcode#56]
## Description

Markdown.ToHtml method throws nullreferenceexception when this package is loaded.

I'm seeing a package warning on restore of :-
warning NU1701: Package 'ColorCode.Portable 1.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NET 
Framework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net6.0'. This package may not be full 
y compatible with your project but a prior issue opened states that only net6.0 is supported, so this is surprising :) 

## Expected Behaviour

Render the markdown as happens when this extension is not loaded.

## Actual Behaviour

throws nullreferenceexception

## Affected Version

1.0.3

## Steps to Reproduce

1. Create empty .net 6.0 project
1. Paste the below code
  using Markdig;
  using Markdown.ColorCode;
  
  internal class Program
  {
      private static void Main(string[] args)
      {
          var inlocation = "C:\\Source\\Personal\\SiteV3\\SiteData";
          var outlocation = "C:\\Source\\Personal\\SiteV3\\Generated";
  
          var pipeline = new MarkdownPipelineBuilder()
              .UseColorCode()
              .UseAdvancedExtensions()
              .Build();
  
          foreach (string fi in Directory.EnumerateFiles(inlocation))
          {
              if (fi.EndsWith(".md"))
              {
                  var text = File.ReadAllText(fi);
                  var html = Markdig.Markdown.ToHtml(text, pipeline);
                  File.WriteAllText(fi.Replace(".md", ".html").Replace(inlocation, outlocation), html);
              }
          }
      }
  }
1. Create the appropriate folder structure and save the markdown file below.
# Title Goes Here
## Subtitle Goes Here

This is a comment *in bold*
Link to page 2: [Page 2](Page2.md)

Image of a cat goes here ![](Images/cat.jpg)

```csharp
using epicness; 
namespace funky
{
    public class chicken : animal
    {
        public chicken()
        {
            this.name = "chicken";
        }
    }
}

```

That was some embedded csharp code. 

## Checklist

- [X] I have read the [contributing guidelines](https://github.com/wbaldoumas/markdown-colorcode/blob/main/CONTRIBUTING.md)
- [X ] I have verified this does not duplicate an existing issue

**Comment by wbaldoumas** [comment]
Thanks for reporting, @WillEastbury! I'll give this a look. Could you provide a sample of what the data in your `SiteData` directory looks like?

**Comment by WillEastbury** [comment]
I have put it into the note above. I've also now noticed that a number of the other extensions seem to throw here as well. So I'm not sure the problem is with markdown-colorcode. 

I'll attach a sample file in a moment.

**Comment by WillEastbury** [comment]
[Will.md](https://github.com/wbaldoumas/markdown-colorcode/files/9352338/Will.md)

**Comment by wbaldoumas** [comment]
@WillEastbury  I've _finally_ gotten around to poking around at this issue you opened here and tested this out first hand (thank you for including your code snippet to replicate). I'm seeing the same issue of a `NullReferenceException` being thrown.

This doesn't appear to be thrown from the `Markdown.ColorCode` library and is being thrown by `Markdig` itself under certain conditions. This only happens when you call `UseAdvancedExtensions()` _after_ `UseColorCode`. With the following sequence of builder calls, I don't get that `NullReferenceException` that you pointed out.

```csharp
var pipeline = new MarkdownPipelineBuilder()
    .UseAdvancedExtensions()
    .UseColorCode()
    .Build();
```

My guess is that the `UseAdvancedExtensions()` is setting something in `Markdig` to null. Let me know if this addresses the issues you were seeing. I'm also going to look into that package restore warning you mentioned.
