### ISSUE TITLE
Please support same nuget targets as Markdig

### ISSUE THREAD

**Issue by stevencohn** [wbaldoumas/markdown-colorcode#71]
## Problem Statement

markdown-colorcode nuget is only supported on .NET 6

## Proposed Solution

Target environments supported by markdig

<img width="152" alt="image" src="https://user-images.githubusercontent.com/9964757/203362591-22cfbd85-9fa2-4345-8d58-a055ae05422f.png">

**Comment by wbaldoumas** [comment]
@stevencohn I don't currently plan on targeting lower framework versions. Do you have a project which requires this?

**Comment by stevencohn** [comment]
Yes @wbaldoumas, [OneMore](https://github.com/stevencohn/OneMore) is a OneNote add-in that needs to run under .NET Framework due to various reasons. I'm using Markdig now but would like to include colorcode as well.

**Comment by wbaldoumas** [comment]
@stevencohn I've published a preview version that provides multi-targeting for .NET Standard 2.0, .NET Standard 2.1, .NET 6.0, and .NET 7.0. 

The .NET Standard target framework additions provide support for applications running on .NET Framework 4.6.2 and above. I don't plan on targeting .NET Framework 4.5.2 directly, since that went out of support on April 26, 2022 and can be considered as insecure. I also will not be targeting .NET Core 3.1 since it goes out of support in less than a week. 😅 

Please give version `1.2.0-preview-2` of this package a try and let me know how it goes. 👍🏻

**Comment by stevencohn** [comment]
Thank you kindly. I will give it a try as soon as I get a chance.
