### ISSUE TITLE
Compatibility with markdig.wpf

### ISSUE THREAD

**Issue by rzinnatullin** [wbaldoumas/markdown-colorcode#84]
## Problem Statement

Syntax highlighting does not work when rendering to FlowDocument with https://github.com/Kryptos-FR/markdig.wpf

## Proposed Solution

In ```readme.md``` explicitly mention that this library supports only built-in HTML renderer.

**Comment by wbaldoumas** [comment]
@rzinnatullin I don't think it's worth adding that level of specificity to the readme here, since this library makes no indication that it is intended to work with anything third-party extensions or anything other than the base [Markdig](https://github.com/xoofx/markdig) library. The [usage](https://github.com/wbaldoumas/markdown-colorcode#usage) section of the readme also shows that this is only intended for the `ToHtml` functionality.

If you disagree, you're welcome to open a pull request that adjusts the readme to be clearer. 😄
